name: CI - Test&Build
on: [ push,  pull_request, workflow_dispatch ]

jobs:
  build:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Test g-cli
        shell: bash
        run: g-cli echo -- "Hello World"
      
